---
name: Tag on CLI Version Change
branding:
  icon: package
  color: green
description: Creates a new Git tag whenever the cli version has changed.
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        #!/bin/bash
        set -euox pipefail

        TAG="$(cat cmd/go_go_gadget/root.go | grep "var version = " | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/')"

        echo -e "TAG: $TAG"
        echo -e "GIT_USER_NAME: $GIT_USER_NAME"
        echo -e "GIT_USER_EMAIL: $GIT_USER_EMAIL"

        # In case only a shallow clone was done
        git fetch --tags

        if ! git tag | grep "${TAG}"; then
          git config user.name ${GIT_USER_NAME}
          git config user.email ${GIT_USER_EMAIL}

          git tag -a ${TAG} -m ${TAG}
          git push --follow-tags
        else
          echo "'${TAG}' already exists. No action taken."
        fi
      env:
        GIT_USER_NAME: ${{ github.event.head_commit.author.username }}
        GIT_USER_EMAIL: ${{ github.event.head_commit.author.email }}
