---
# This workflow tags on pushes to main
#
# https://github.com/marketplace/actions/create-tags-from

name: Tag and Release
on:
    push:
        branches: ["main"]
jobs:
    tag:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # - name: Load Current Version
            #   id: get_version
            #   run: echo "::set-output name=version::$(cat cmd/go_go_gadget/root.go | grep "var version = " | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/')"

            - name: Create Tag
              id: createtag
              uses: ./.github/actions/tag

            - name: Show createtag Outputs
              run:   echo "$OUTPUTS"
              shell: bash
              env:
                OUTPUTS: ${{ toJSON(steps.createtag.outputs) }}

            - name: Create Release
              if: steps.createtag.output.newtag == true
              id: createrelease
              uses: actions/create-release@latest
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ steps.createtag.outputs.version }}
                release_name: Release v${{ steps.createtag.outputs.version }}
                draft: false
                prerelease: false
